# Generated by Django 4.1.1 on 2022-12-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
